using System.Collections.ObjectModel;
using System.Text.Json.Serialization;

namespace TypeSafe.AI;

/// <summary>
/// Token usage reported by the TypeSafe API for an evaluation request.
/// </summary>
public sealed record TypeSafeUsage
{
    /// <summary>
    /// Gets the number of input tokens consumed by the evaluation, or <see langword="null"/> if not reported.
    /// </summary>
    [JsonPropertyName("input_tokens")] public int? InputTokens { get; init; }

    /// <summary>
    /// Gets the number of output tokens generated by the evaluation, or <see langword="null"/> if not reported.
    /// </summary>
    [JsonPropertyName("output_tokens")] public int? OutputTokens { get; init; }
}

/// <summary>
/// The system-one evaluation request payload. Use <see cref="Create"/> to validate and snapshot inputs.
/// </summary>
public sealed record SystemOneRequest
{
    /// <summary>
    /// Gets the input content to evaluate (string, JSON object, or JSON array).
    /// </summary>
    public required TypeSafeContent State { get; init; }

    /// <summary>
    /// Gets the identifier of the model to evaluate questions with (e.g. "jev-latest").
    /// </summary>
    public required string Model { get; init; }

    /// <summary>
    /// Gets the dictionary of questions keyed by caller-chosen question identifiers.
    /// </summary>
    public required IReadOnlyDictionary<string, TypeSafeQuestion> Questions { get; init; }

    /// <summary>
    /// Validates the inputs against the API contract and creates a defensive, immutable snapshot.
    /// </summary>
    /// <param name="state">The content to evaluate.</param>
    /// <param name="questions">Questions keyed by caller-chosen ids (must contain at least 1 question).</param>
    /// <param name="model">The model name to execute.</param>
    /// <returns>A validated, immutable <see cref="SystemOneRequest"/> instance.</returns>
    public static SystemOneRequest Create(TypeSafeContent state,
        IReadOnlyDictionary<string, TypeSafeQuestion> questions, string model)
    {
        ArgumentNullException.ThrowIfNull(state);
        ArgumentException.ThrowIfNullOrWhiteSpace(model);
        return new SystemOneRequest { State = state, Model = model, Questions = SnapshotQuestions(questions) };
    }

    internal static IReadOnlyDictionary<string, TypeSafeQuestion> SnapshotQuestions(IReadOnlyDictionary<string, TypeSafeQuestion> questions)
    {
        ArgumentNullException.ThrowIfNull(questions);
        if (questions.Count == 0)
            throw new ArgumentException("At least one question is required.", nameof(questions));

        var snapshot = new Dictionary<string, TypeSafeQuestion>(questions.Count);
        foreach (var (id, question) in questions)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(id);
            if (question is null || question.Instructions is null)
                throw new ArgumentException($"The question '{id}' requires non-null instructions.", nameof(questions));
            snapshot[id] = question switch
            {
                null => throw new ArgumentException($"The question '{id}' is null.", nameof(questions)),
                Noul => question,
                Choice { Criteria: var criteria } => SnapshotChoice(id, question.Instructions, criteria),
                Score { Criteria: var levels } => SnapshotScore(id, question.Instructions, levels),
                _ => throw new ArgumentException($"The question '{id}' has an unsupported type {question.GetType().Name}.", nameof(questions))
            };
        }
        return new ReadOnlyDictionary<string, TypeSafeQuestion>(snapshot);
    }

    private static TypeSafeQuestion SnapshotChoice(string id, TypeSafeContent instructions,
        IReadOnlyDictionary<string, TypeSafeContent?> criteria)
    {
        ArgumentNullException.ThrowIfNull(criteria);
        if (criteria.Count is < 1 or > 255)
            throw new ArgumentException($"The choice question '{id}' requires between 1 and 255 options.");
        foreach (var label in criteria.Keys)
            ArgumentException.ThrowIfNullOrWhiteSpace(label);
        return new Choice
        {
            Instructions = instructions,
            Criteria = new ReadOnlyDictionary<string, TypeSafeContent?>(new Dictionary<string, TypeSafeContent?>(criteria))
        };
    }

    private static TypeSafeQuestion SnapshotScore(string id, TypeSafeContent instructions,
        IReadOnlyList<TypeSafeContent> criteria)
    {
        ArgumentNullException.ThrowIfNull(criteria);
        if (criteria.Count is < 2 or > 10)
            throw new ArgumentException($"The score question '{id}' requires between 2 and 10 rubric levels.");
        for (var index = 0; index < criteria.Count; index++)
        {
            if (criteria[index] is null)
                throw new ArgumentException($"The score question '{id}' has a null rubric level at index {index}.");
        }
        return new Score { Instructions = instructions, Criteria = Array.AsReadOnly(criteria.ToArray()) };
    }
}

/// <summary>
/// An immutable evaluation response containing the model's answers, token usage, and request metadata.
/// </summary>
[JsonConverter(typeof(SystemOneResponseJsonConverter))]
public sealed class SystemOneResponse
{
    /// <summary>
    /// Gets the model identifier that answered the evaluation request.
    /// </summary>
    public string Model { get; }

    /// <summary>
    /// Gets all returned answers keyed by question identifier, including any unrecognized answer types.
    /// </summary>
    public IReadOnlyDictionary<string, TypeSafeAnswer> Answers { get; }

    /// <summary>
    /// Gets the token usage statistics reported for the evaluation.
    /// </summary>
    public TypeSafeUsage Usage { get; }

    /// <summary>
    /// Gets the server-assigned request ID (from the x-typesafe-request-id response header), if available.
    /// </summary>
    public string? RequestId { get; }

    /// <summary>
    /// Gets a filtered dictionary of all yes/no (<see cref="NoulAnswer"/>) answers keyed by question identifier.
    /// </summary>
    public IReadOnlyDictionary<string, NoulAnswer> Nouls { get; }

    /// <summary>
    /// Gets a filtered dictionary of all multiple-choice (<see cref="ChoiceAnswer"/>) answers keyed by question identifier.
    /// </summary>
    public IReadOnlyDictionary<string, ChoiceAnswer> Choices { get; }

    /// <summary>
    /// Gets a filtered dictionary of all rubric score (<see cref="ScoreAnswer"/>) answers keyed by question identifier.
    /// </summary>
    public IReadOnlyDictionary<string, ScoreAnswer> Scores { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SystemOneResponse"/> class.
    /// </summary>
    /// <param name="model">The model that evaluated the questions.</param>
    /// <param name="answers">All answers returned by the model.</param>
    /// <param name="usage">Token usage statistics.</param>
    /// <param name="requestId">The server-assigned request ID, if present.</param>
    public SystemOneResponse(string model, IReadOnlyDictionary<string, TypeSafeAnswer> answers,
        TypeSafeUsage usage, string? requestId = null)
    {
        ArgumentNullException.ThrowIfNull(model);
        ArgumentNullException.ThrowIfNull(answers);
        ArgumentNullException.ThrowIfNull(usage);
        Model = model;
        Usage = usage;
        RequestId = requestId;
        var all = new Dictionary<string, TypeSafeAnswer>(answers.Count);
        var nouls = new Dictionary<string, NoulAnswer>();
        var choices = new Dictionary<string, ChoiceAnswer>();
        var scores = new Dictionary<string, ScoreAnswer>();
        foreach (var (id, answer) in answers)
        {
            ArgumentNullException.ThrowIfNull(answer);
            var copy = answer switch
            {
                ChoiceAnswer choice => Snapshot(choice),
                ScoreAnswer score => Snapshot(score),
                UnknownAnswer unknown => unknown with { Raw = unknown.Raw.Clone() },
                _ => answer
            };
            all.Add(id, copy);
            switch (copy)
            {
                case NoulAnswer noul: nouls.Add(id, noul); break;
                case ChoiceAnswer choice: choices.Add(id, choice); break;
                case ScoreAnswer score: scores.Add(id, score); break;
            }
        }
        Answers = new ReadOnlyDictionary<string, TypeSafeAnswer>(all);
        Nouls = new ReadOnlyDictionary<string, NoulAnswer>(nouls);
        Choices = new ReadOnlyDictionary<string, ChoiceAnswer>(choices);
        Scores = new ReadOnlyDictionary<string, ScoreAnswer>(scores);
    }

    private static ChoiceAnswer Snapshot(ChoiceAnswer answer)
    {
        ArgumentNullException.ThrowIfNull(answer.Choice);
        return answer with { Probabilities = Copy(answer.Probabilities) };
    }

    private static ScoreAnswer Snapshot(ScoreAnswer answer)
    {
        ArgumentNullException.ThrowIfNull(answer.Legend);
        foreach (var value in answer.Legend.Values) ArgumentNullException.ThrowIfNull(value);
        return answer with { Legend = Copy(answer.Legend), Probabilities = Copy(answer.Probabilities) };
    }

    private static IReadOnlyDictionary<string, T> Copy<T>(IReadOnlyDictionary<string, T> values)
    {
        ArgumentNullException.ThrowIfNull(values);
        return new ReadOnlyDictionary<string, T>(new Dictionary<string, T>(values));
    }
}

/// <summary>
/// The general-purpose TypeSafe System One client, mirroring the official SDKs.
/// When resolved via dependency injection, transport lifetimes are managed automatically
/// by <see cref="IHttpClientFactory"/> (do not dispose).
/// For standalone usage outside DI, instantiate <see cref="TypeSafeClient"/> directly
/// which implements <see cref="IDisposable"/>.
/// </summary>
public interface ITypeSafeClient
{
    /// <summary>Evaluates a pre-built, immutable System One request in one upstream call.</summary>
    /// <param name="request">The validated, immutable System One request.</param>
    /// <param name="cancellationToken">Propagates caller cancellation.</param>
    /// <returns>The provider's answers, usage statistics, and request metadata.</returns>
    /// <exception cref="TypeSafeAuthenticationException">Authentication failed (401).</exception>
    /// <exception cref="TypeSafeValidationException">The request was rejected (422).</exception>
    /// <exception cref="TypeSafeRateLimitException">Rate limit exceeded (429).</exception>
    /// <exception cref="TypeSafeOverloadedException">Service temporarily overloaded (529).</exception>
    /// <exception cref="TypeSafeTimeoutException">Per-attempt or total timeout budget exceeded.</exception>
    /// <exception cref="TypeSafeConnectionException">Network transport or read failure.</exception>
    /// <exception cref="TypeSafeProtocolException">Invalid response format from the server.</exception>
    Task<SystemOneResponse> SystemOneAsync(SystemOneRequest request,
        CancellationToken cancellationToken = default);

    /// <summary>Evaluates the state against the questions in one upstream request.</summary>
    /// <param name="state">The content to evaluate: a string, object, or array.</param>
    /// <param name="questions">Questions keyed by caller-chosen ids; must be nonempty.</param>
    /// <param name="model">Per-call model override; null uses the configured default.</param>
    /// <param name="cancellationToken">Propagates caller cancellation.</param>
    /// <returns>The provider's answers, usage statistics, and request metadata.</returns>
    /// <exception cref="TypeSafeAuthenticationException">Authentication failed (401).</exception>
    /// <exception cref="TypeSafeValidationException">The request was rejected (422).</exception>
    /// <exception cref="TypeSafeRateLimitException">Rate limit exceeded (429).</exception>
    /// <exception cref="TypeSafeOverloadedException">Service temporarily overloaded (529).</exception>
    /// <exception cref="TypeSafeTimeoutException">Per-attempt or total timeout budget exceeded.</exception>
    /// <exception cref="TypeSafeConnectionException">Network transport or read failure.</exception>
    /// <exception cref="TypeSafeProtocolException">Invalid response format from the server.</exception>
    Task<SystemOneResponse> SystemOneAsync(TypeSafeContent state,
        IReadOnlyDictionary<string, TypeSafeQuestion> questions, string? model = null,
        CancellationToken cancellationToken = default);
}

